<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Absensi New</name>
   <tag></tag>
   <elementGuidId>0f7d0da2-7f22-4446-b39a-8c3edec53932</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_add_new']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_add_new</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>31784c0a-e23c-4fb7-ac7b-4d0d4b057cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flat btn-success btn_add_new</value>
      <webElementGuid>57af1bb6-0fd0-45e1-bca7-9f05a8096823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_add_new</value>
      <webElementGuid>5b5cb5b7-c85e-4747-9330-cb008b2ffe6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:80/cicool/administrator/absensi/add</value>
      <webElementGuid>ae90a040-a872-427f-ad7b-4c716feaee7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Add Absensi New  (Ctrl+a)</value>
      <webElementGuid>699f3783-5954-484c-83e2-d73f76f9b47d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip310436</value>
      <webElementGuid>cfa5953f-e02e-4167-a07b-8bfbe7360c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add Absensi New</value>
      <webElementGuid>a8bb67d6-71ce-4352-8b5a-4f2ac2806717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_add_new&quot;)</value>
      <webElementGuid>a86eaa19-9e7a-41da-816f-581659655d73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_add_new']</value>
      <webElementGuid>9c84ad52-3e00-4034-8101-95b684d8f40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/section[2]/div/div/div/div/div/div/div/a</value>
      <webElementGuid>a0807570-59af-4089-99de-2e9deb381547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Absensi New')]</value>
      <webElementGuid>db997f22-2359-42ac-98bc-d57844a77ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Absensi'])[1]/following::a[1]</value>
      <webElementGuid>4628f1c4-2da0-4c72-ae9f-6a573627160f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register All'])[1]/following::a[2]</value>
      <webElementGuid>57f60084-ba86-4004-a27d-a530925baf8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Absensi New']/parent::*</value>
      <webElementGuid>6faf6ba7-ec8e-4523-bd3d-f50287da517e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:80/cicool/administrator/absensi/add']</value>
      <webElementGuid>f7c59a79-d0f9-404e-a21d-9b55237e11fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a</value>
      <webElementGuid>fdc66aab-3b0e-4e1e-8a0c-baf91b9ea631</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_add_new' and @href = 'http://localhost:80/cicool/administrator/absensi/add' and (text() = ' Add Absensi New' or . = ' Add Absensi New')]</value>
      <webElementGuid>924b92a9-ed46-48ff-a21d-faaa4ef374c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
