<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ins_Filter_iCheck-helper</name>
   <tag></tag>
   <elementGuidId>6f24038b-fcd5-4504-b08f-f5e5f7a416ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form_absensi']/div[2]/table/thead/tr/th/div/ins</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ins.iCheck-helper</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ins</value>
      <webElementGuid>1b0f6331-a2c6-40d5-a536-cdfd2f57e127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>iCheck-helper</value>
      <webElementGuid>ca0d297f-02aa-4852-a833-ccd53af2db87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_absensi&quot;)/div[@class=&quot;table-responsive&quot;]/table[@class=&quot;table table-bordered table-striped dataTable&quot;]/thead[1]/tr[1]/th[1]/div[@class=&quot;icheckbox_minimal-red focus hover&quot;]/ins[@class=&quot;iCheck-helper&quot;]</value>
      <webElementGuid>c0b2d8ba-71f7-4ea7-805a-857179d2807f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_absensi']/div[2]/table/thead/tr/th/div/ins</value>
      <webElementGuid>b68d074d-6e4c-4676-8e1c-86942b93ede6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ins</value>
      <webElementGuid>3b97f280-0f21-42f6-bfab-446ba19b8785</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
