<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_see_absensi</name>
   <tag></tag>
   <elementGuidId>40e21b5f-69fa-447d-b530-816bbd0b9048</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[@id='tbody_crud']/tr/td[5]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.label-default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0e82c495-e3ab-46a8-8aae-2eb46c11a2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://localhost:80/cicool/administrator/absensi</value>
      <webElementGuid>5bceec8f-27bf-4ddb-b3e7-db8e6aff42f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-default</value>
      <webElementGuid>0a794ecb-a4e5-4543-b67c-3e83ae52c5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> see                                                                                           </value>
      <webElementGuid>0581c9b2-4ebd-4e58-8dc8-5719641111f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbody_crud&quot;)/tr[1]/td[5]/a[@class=&quot;label-default&quot;]</value>
      <webElementGuid>b28b33fe-ce77-4f1b-b58f-42c42805d37c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='tbody_crud']/tr/td[5]/a</value>
      <webElementGuid>874ba6f7-da8a-4686-9c64-8855ca95e3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'see')]</value>
      <webElementGuid>839ae316-dc8b-4ebd-8c01-c73d2953a8b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='absensi'])[1]/following::a[1]</value>
      <webElementGuid>34711eaa-d0e1-4770-a28e-5ade6b400ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Absensi'])[2]/following::a[1]</value>
      <webElementGuid>5a132c3f-d5ef-40ad-8295-63fa478edbd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change'])[1]/preceding::a[1]</value>
      <webElementGuid>dcd1e470-501a-4243-b3a3-ca13c9aa154d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::a[2]</value>
      <webElementGuid>2db403ef-4798-456c-82d6-fd5abb09a86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='see']/parent::*</value>
      <webElementGuid>9080e515-562a-4fc2-839d-a99e9170fb48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://localhost:80/cicool/administrator/absensi']</value>
      <webElementGuid>47e4b3b8-51b8-4f01-a45e-fb1111e14aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/a</value>
      <webElementGuid>7a293e00-9e19-4110-a6ca-e938c9d6734a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://localhost:80/cicool/administrator/absensi' and (text() = ' see                                                                                           ' or . = ' see                                                                                           ')]</value>
      <webElementGuid>c988840c-8286-410b-b0b7-869da13b1b31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
