<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Save and go to list</name>
   <tag></tag>
   <elementGuidId>9982414d-839f-4fb7-92a5-f853a2c56cb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn_save']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>79e071b6-191e-45ce-937c-663eca251d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flat btn-info btn_save btn_action btn_save_back</value>
      <webElementGuid>c95487ec-5149-45d1-b3de-4e19a5aa137d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_save</value>
      <webElementGuid>0bd85ab0-5484-4d40-b82a-814cc9e86120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-stype</name>
      <type>Main</type>
      <value>back</value>
      <webElementGuid>5fcb9563-1aa0-4f2d-8bad-e003044ad545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Save and go to list (Ctrl+d)</value>
      <webElementGuid>7dca9063-39b3-4af2-a697-32425d7b1428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip923936</value>
      <webElementGuid>4a2a80fc-fa67-41e9-bfbd-8cf0dae10662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                 Save and go to list                            </value>
      <webElementGuid>9188354a-0d63-4d9f-8b7b-4be72ae4d5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form_absensi&quot;)/div[@class=&quot;row-fluid col-md-7 container-button-bottom&quot;]/a[@id=&quot;btn_save&quot;]</value>
      <webElementGuid>285ae707-19fc-457d-bfe8-b3799bcce97f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn_save']</value>
      <webElementGuid>6aff608a-ca83-415f-886c-9bb0268ef12d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form_absensi']/div[5]/a</value>
      <webElementGuid>a3c1e3af-b9d8-47a0-ae7a-5c9f8402fee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Input Location'])[1]/following::a[1]</value>
      <webElementGuid>e690ee83-8056-4a1b-b9b1-ac8cd7e8d2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save and go to list (Ctrl+d)'])[1]/preceding::a[1]</value>
      <webElementGuid>8dd51f17-11b5-426b-b24e-86eb193b201e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save and go to list']/parent::*</value>
      <webElementGuid>8d194b02-2bb9-4aa3-bd23-5c2e5c7dd066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>bc5c4a0e-b4d7-43f8-8699-ce2a43500497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btn_save' and (text() = '
                                 Save and go to list                            ' or . = '
                                 Save and go to list                            ')]</value>
      <webElementGuid>7be922a8-19d7-4c2a-85c1-f5a5101fc347</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
